version: '3'

services:
  neo4j:
    image: neo4j:4.4.7
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./runtime/data:/data
      - ./runtime/logs:/logs
      - ./runtime/plugins:/var/lib/neo4j/plugins
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*

  redis-cache:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel notice
    volumes:
      - cache:/data
    links:
      - redis-commander

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis-cache
      REDIS_HOST: redis-cache
      REDIS_PORT: redis-cache:6379
      REDIS_PASSWORD: 
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081

  depvis-next:
    depends_on:
      - neo4j
      - redis-cache
    build: ./src/depvis-next
    image: depvis-next:latest
    ports:
      - 8123:3000
    restart: always
volumes:
  cache:
    driver: local
