version: '3'

services:
  neo4j:
    image: neo4j:4.4.7
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./runtime/data:/data
      - ./runtime/logs:/logs
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/test

  # depvis-frontend:
  #   depends_on:
  #     - neo4j
  #   build: ./src/depvis-frontend
  #   image: depvis-frontend:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always
