version: '3'

services:
  neo4j:
    image: neo4j:4.4.7
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./runtime/data:/data
      - ./runtime/logs:/logs
      - ./runtime/plugins:/var/lib/neo4j/plugins
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*

  redis-cache:
    image: redis:alpine
    restart: unless-stopped
    ports: 
      - 6379:6379
    command: redis-server --save 20 1 --loglevel notice
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local

  # depvis-next:
  #   depends_on:
  #     - neo4j
  #   build: ./src/depvis-next
  #   image: depvis-next:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always
